# Generated by Django 3.0.7 on 2020-07-04 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Payment'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('NO', 'Select Category'), ('CM', 'Coffee Machines'), ('CT', 'Coffee Tools'), ('CC', 'Coffee Cups'), ('IC', 'Imported Coffee')], default='SELECT CATEGORY', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('NO', 'Select Category'), ('CM', 'Coffee Machines'), ('CT', 'Coffee Tools'), ('CC', 'Coffee Cups'), ('IC', 'Imported Coffee')], max_length=3),
        ),
    ]
